### ISSUE TITLE
getTotalWeight() should not be rounded

### ISSUE THREAD

**Issue by RuChiang** [RuChiang/Market_Place#16]

**Comment by AjitZK** [comment]
Heads up, if you look at the solution right now... rounding is not going to affect the functionality, but only the UI

**Comment by RuChiang** [comment]
but it still does not make sense because the user will have the button disable despite the shown totalweight being within the limit

**Comment by RuChiang** [comment]
fixed in 01ef204c608dd8312304b4bc1629aeca66926bd6
